package conformance

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/zeebo/blake3"

	"decentralized.host/pkg/audit"
	"decentralized.host/pkg/canon"
	"decentralized.host/pkg/capability"
	"decentralized.host/pkg/envelope"
	"decentralized.host/pkg/identity"
	"decentralized.host/pkg/storage"
)

// Protocol identifies the suite.
const Protocol = "dh/v1"

// SuiteVersion changes whenever vectors are added or change meaning.
const SuiteVersion = 1

// Suite is the vector file.
type Suite struct {
	Protocol string   `json:"protocol"`
	Version  int      `json:"version"`
	Note     string   `json:"note"`
	Vectors  []Vector `json:"vectors"`
}

// Vector is one test case. Expect is {"output": …} or {"error": "<code>"}.
type Vector struct {
	ID          string          `json:"id"`
	Op          string          `json:"op"`
	Description string          `json:"description"`
	Input       json.RawMessage `json:"input"`
	Expect      json.RawMessage `json:"expect"`
}

// Seed returns the hex seed of conformance identity n:
// BLAKE3("decentralized.host/conformance-seed/v1" || n)[:32].
func Seed(n byte) string {
	sum := blake3.Sum256(append([]byte("decentralized.host/conformance-seed/v1"), n))
	return hex.EncodeToString(sum[:32])
}

func ident(n byte) *identity.Identity {
	b, _ := hex.DecodeString(Seed(n))
	return identity.FromSeed(b)
}

// GenData materializes a "data_gen" input: xorshift64* seeded with seed,
// each step emitting 8 little-endian bytes, truncated to length; alg "zero"
// is length zero bytes; alg "pattern" repeats the bytes 0..250.
func GenData(alg string, seed uint64, length int) ([]byte, error) {
	out := make([]byte, length)
	switch alg {
	case "zero":
	case "pattern":
		for i := range out {
			out[i] = byte(i % 251)
		}
	case "xorshift64*":
		x := seed
		if x == 0 {
			return nil, errors.New("xorshift64* seed must be non-zero")
		}
		var w [8]byte
		for i := 0; i < length; i += 8 {
			x ^= x >> 12
			x ^= x << 25
			x ^= x >> 27
			binary.LittleEndian.PutUint64(w[:], x*0x2545F4914F6CDD1D)
			copy(out[i:], w[:])
		}
	default:
		return nil, fmt.Errorf("unknown data_gen alg %q", alg)
	}
	return out, nil
}

// Materialize expands generator shorthands in an input before it is sent
// to an adapter: {"data_gen":{"alg","seed","length"}} becomes {"data_b64"}.
func Materialize(op string, in json.RawMessage) (json.RawMessage, error) {
	if op != "chunk" {
		return in, nil
	}
	var r struct {
		Gen *struct {
			Alg    string `json:"alg"`
			Seed   uint64 `json:"seed"`
			Length int    `json:"length"`
		} `json:"data_gen"`
	}
	if err := json.Unmarshal(in, &r); err != nil || r.Gen == nil {
		return in, err
	}
	data, err := GenData(r.Gen.Alg, r.Gen.Seed, r.Gen.Length)
	if err != nil {
		return nil, err
	}
	return json.Marshal(map[string]any{"data_b64": data})
}

type gen struct {
	s   Suite
	err error
}

func (g *gen) add(op, id, desc string, input any) {
	if g.err != nil {
		return
	}
	raw, err := canon.Wire(input)
	if err != nil {
		g.err = fmt.Errorf("%s: %w", id, err)
		return
	}
	sent, err := Materialize(op, raw)
	if err != nil {
		g.err = fmt.Errorf("%s: %w", id, err)
		return
	}
	out, herr := Handle(op, sent)
	var expect any
	if herr != nil {
		var e *Error
		if !errors.As(herr, &e) || e.Code == CodeBadInput {
			g.err = fmt.Errorf("%s: reference adapter: %v", id, herr)
			return
		}
		expect = map[string]any{"error": e.Code}
	} else {
		expect = map[string]any{"output": out}
	}
	eb, err := canon.Marshal(expect)
	if err != nil {
		g.err = fmt.Errorf("%s: %w", id, err)
		return
	}
	g.s.Vectors = append(g.s.Vectors, Vector{ID: op + "/" + id, Op: op, Description: desc, Input: raw, Expect: eb})
}

// Generate builds the full, deterministic vector suite with the Go
// reference implementation.
func Generate() (*Suite, error) {
	g := &gen{s: Suite{Protocol: Protocol, Version: SuiteVersion,
		Note: "Generated by dh-conformance gen from the Go reference implementation. Do not edit by hand; see docs/protocol/conformance.md."}}
	genCanon(g)
	genIdentity(g)
	genHashes(g)
	genEnvelopes(g)
	genAudit(g)
	genCapabilities(g)
	genStorage(g)
	if g.err != nil {
		return nil, g.err
	}
	return &g.s, nil
}

func b(s string) []byte { return []byte(s) }

func genCanon(g *gen) {
	bs := `\`
	cases := []struct {
		id, desc string
		raw      []byte
	}{
		{"sort-keys", "object keys are sorted", b(`{"b":1,"a":2,"c":{"z":0,"y":[3,2,1]}}`)},
		{"whitespace", "insignificant whitespace is removed", b(" {\n\t\"a\" : [ 1 , 2 ] ,\r\n \"b\" : { } } ")},
		{"empty", "empty containers", b(`{"a":{},"b":[]}`)},
		{"scalars", "top-level scalars are valid documents", b(` "x" `)},
		{"true", "literal true", b(`true`)},
		{"null", "literal null", b(`null`)},
		{"array-order", "array order is preserved", b(`[3,1,2,{"b":0,"a":0}]`)},
		{"key-byte-order", "keys sort by UTF-8 byte order (= code point order)", b(`{"é":1,"z":2,"Z":3,"😀":4,"ﬀ":5,"a":6,"":7}`)},
		{"escape-unicode", "\\u escapes of printable characters are emitted raw", b(`"` + bs + `u00e9` + bs + `u4e2d` + bs + `/"`)},
		{"escape-short", "short escapes for \\b \\f \\n \\r \\t", b(`"` + bs + `u0008` + bs + `u000c` + bs + `n` + bs + `r` + bs + `t"`)},
		{"escape-control", "other controls use lowercase \\u00xx", b(`"` + bs + `u0001` + bs + `u001F` + bs + `u0000"`)},
		{"escape-quote-backslash", "quote and backslash", b(`"a` + bs + `"b` + bs + bs + `c"`)},
		{"raw-del-and-separators", "U+007F, U+2028, U+2029 and <>& are emitted raw", b(`"` + bs + `u007f` + bs + `u2028` + bs + `u2029<>&"`)},
		{"surrogate-pair", "an escaped surrogate pair becomes one raw code point", b(`"` + bs + `ud83d` + bs + `ude00"`)},
		{"neg-zero", "-0 is the integer 0", b(`[-0,0]`)},
		{"max-safe", "±(2^53-1) are allowed", b(`[9007199254740991,-9007199254740991]`)},
		{"escaped-key-order", "keys compare after unescaping", b(`{"` + bs + `u0062":1,"a":2}`)},
		{"same-key-different-objects", "the same key in different objects is fine", b(`{"a":{"a":1},"b":{"a":2}}`)},
		{"reject-float", "fractions are not allowed", b(`{"a":1.0}`)},
		{"reject-exponent", "exponents are not allowed", b(`[1e2]`)},
		{"reject-exponent-upper", "exponents are not allowed", b(`[1E2]`)},
		{"reject-too-large", "2^53 is outside the safe range", b(`[9007199254740992]`)},
		{"reject-too-small", "-(2^53) is outside the safe range", b(`[-9007199254740992]`)},
		{"reject-huge", "integers beyond 64 bits", b(`[123456789012345678901234567890]`)},
		{"reject-duplicate", "duplicate keys are rejected", b(`{"a":1,"a":1}`)},
		{"reject-duplicate-escaped", "duplicates are detected after unescaping", b(`{"a":1,"` + bs + `u0061":2}`)},
		{"reject-duplicate-nested", "duplicates in nested objects", b(`[{"x":{"k":1,"k":2}}]`)},
		{"reject-trailing", "one JSON value per document", b(`{} {}`)},
		{"reject-nan", "NaN is not JSON", b(`[NaN]`)},
		{"reject-infinity", "Infinity is not JSON", b(`[Infinity]`)},
		{"reject-leading-zero", "leading zeros are not JSON", b(`[01]`)},
		{"reject-syntax", "syntax errors", b(`{"a":}`)},
		{"reject-single-quote", "single-quoted strings", b(`{'a':1}`)},
		{"reject-trailing-comma", "trailing commas", b(`[1,2,]`)},
		{"reject-lone-high-surrogate", "an unpaired high surrogate escape", b(`"` + bs + `ud800"`)},
		{"reject-lone-low-surrogate", "an unpaired low surrogate escape", b(`"x` + bs + `udc00y"`)},
		{"reject-reversed-surrogates", "low then high surrogate", b(`"` + bs + `ude00` + bs + `ud83d"`)},
		{"reject-invalid-utf8", "raw bytes that are not UTF-8", []byte{'"', 0xff, 0xfe, '"'}},
		{"reject-overlong-utf8", "overlong UTF-8 encoding of '/'", []byte{'"', 0xc0, 0xaf, '"'}},
		{"reject-bom", "a byte order mark is not whitespace", append([]byte{0xef, 0xbb, 0xbf}, `{}`...)},
		{"reject-raw-control", "unescaped control characters inside strings", []byte{'"', 'a', 0x01, '"'}},
		{"reject-empty", "an empty document", b(``)},
	}
	for _, c := range cases {
		g.add("canon", c.id, c.desc, map[string]any{"json_b64": c.raw})
	}
}

func genIdentity(g *gen) {
	for _, n := range []byte{0, 1, 2, 3} {
		g.add("identity", fmt.Sprintf("seed-%d", n), "Ed25519 public key and dh1 id from a 32-byte seed", map[string]any{"seed": Seed(n)})
	}
	g.add("identity", "seed-zero", "all-zero seed", map[string]any{"seed": strings.Repeat("00", 32)})
	zero := make([]byte, 32)
	g.add("identity", "pub-zero", "dh1 id of an arbitrary 32-byte key", map[string]any{"pub": identity.EncodePub(ed25519.PublicKey(zero))})
	g.add("identity", "pub-short", "a 31-byte key is malformed", map[string]any{"pub": base64.RawURLEncoding.EncodeToString(zero[:31])})
	g.add("identity", "pub-padded", "padding is not allowed in wire keys", map[string]any{"pub": identity.EncodePub(ident(1).Pub) + "="})
	g.add("identity", "pub-std-alphabet", "the standard base64 alphabet is not the wire alphabet", map[string]any{"pub": "+" + identity.EncodePub(ident(1).Pub)[1:]})
}

func genHashes(g *gen) {
	vals := []struct{ id, raw string }{
		{"object", `{"b":[1,2,3],"a":"x"}`},
		{"string", `"hello"`},
		{"unicode", `{"name":"Zoë 😀"}`},
		{"empty-object", `{}`},
	}
	for _, v := range vals {
		g.add("digest", v.id, "b3: + hex(BLAKE3-256(canonical(value)))", map[string]any{"value": json.RawMessage(v.raw)})
	}
	g.add("digest", "reorder-invariant", "same digest after key reordering", map[string]any{"value": json.RawMessage(`{"a":"x","b":[1,2,3]}`)})
	g.add("digest", "reject-float", "values without a canonical form have no digest", map[string]any{"value": json.RawMessage(`{"a":0.5}`)})
	for _, d := range []string{"audit", "bundle", "fastcdc-gear"} {
		g.add("domain-hash", d, "BLAKE3 over the signing-domain prefix and canonical value", map[string]any{"domain": d, "value": json.RawMessage(`{"seq":1,"v":"x"}`)})
	}
}

func genEnvelopes(g *gen) {
	id1, id2 := ident(1), ident(2)
	payloads := []struct{ id, kind, raw, signer string }{
		{"enroll", envelope.KindEnroll, `{"node":"` + id1.ID + `","ts":1700000000000,"nonce":"n-1"}`, ""},
		{"assignment", envelope.KindAssignment, `{"id":"web/r0","generation":3,"digest":"b3:00","resources":{"cpuMilli":250,"memBytes":134217728}}`, ""},
		{"html-chars", envelope.KindObservation, `{"detail":"<script>&amp;</script>","path":"a/b"}`, ""},
		{"unicode", envelope.KindFacts, `{"note":"Zoë 😀 \u0001","z":1,"a":[]}`, ""},
		{"rotated-signer", envelope.KindRotation, `{"from":"old","to":"new","seq":2}`, ident(3).ID},
	}
	for _, p := range payloads {
		g.add("sign", p.id, "Ed25519 over \"decentralized.host/<kind>/v1\\n\" + canonical(payload)", map[string]any{"seed": Seed(1), "signer": p.signer, "kind": p.kind, "payload": json.RawMessage(p.raw)})
	}

	good, _ := envelope.Sign(id1, "", envelope.KindAssignment, map[string]any{"b": 2, "a": "<x>", "n": []int{1, 2}})
	enc := func(e *envelope.Envelope) []byte { b, _ := canon.Wire(e); return b }
	clone := func() *envelope.Envelope {
		c := *good
		c.Payload = append(json.RawMessage{}, good.Payload...)
		return &c
	}
	verify := func(id, desc string, raw []byte, kind string, self bool, allowed ...string) {
		in := map[string]any{"envelope_b64": raw, "kind": kind, "self": self, "allowed": allowed}
		if allowed == nil {
			in["allowed"] = []string{}
		}
		g.add("verify", id, desc, in)
	}
	verify("valid-self", "self-certifying: signer is the dh1 id of the embedded key", enc(good), envelope.KindAssignment, true)
	verify("valid-allowed", "embedded key is in the allowed set", enc(good), envelope.KindAssignment, false, id2.PubString(), id1.PubString())
	verify("wrong-kind", "the kind is the signing domain", enc(good), envelope.KindBundle, true)

	reenc := clone()
	reenc.Payload = json.RawMessage("{ \"n\" : [1,2], \"a\" : \"\\u003cx\\u003e\", \"b\" : 2 }")
	verify("transport-reencoded", "verifiers canonicalize the payload first (reordered keys, whitespace, \\u003c escapes)", enc(reenc), envelope.KindAssignment, true)

	tam := clone()
	tam.Payload = json.RawMessage(strings.Replace(string(tam.Payload), `"b":2`, `"b":3`, 1))
	verify("tampered-payload", "one changed value", enc(tam), envelope.KindAssignment, true)

	dup := clone()
	dup.Payload = json.RawMessage(`{"a":"<x>","b":2,"b":2,"n":[1,2]}`)
	verify("duplicate-key-payload", "a payload with duplicate keys has no canonical form", enc(dup), envelope.KindAssignment, true)

	flt := clone()
	flt.Payload = json.RawMessage(`{"a":"<x>","b":2.0,"n":[1,2]}`)
	verify("float-payload", "2.0 is not an integer", enc(flt), envelope.KindAssignment, true)

	short := clone()
	short.Pub = short.Pub[:len(short.Pub)-2]
	verify("malformed-key", "a truncated public key", enc(short), envelope.KindAssignment, true)

	trunc := clone()
	trunc.Sig = trunc.Sig[:len(trunc.Sig)-4]
	verify("truncated-signature", "a short signature", enc(trunc), envelope.KindAssignment, true)

	padded := clone()
	padded.Sig += "=="
	verify("padded-signature", "signatures are unpadded base64url", enc(padded), envelope.KindAssignment, true)

	other := clone()
	other.Pub = id2.PubString()
	other.Signer = id2.ID
	verify("key-substitution", "the embedded key did not produce the signature", enc(other), envelope.KindAssignment, true)

	wrongSigner := clone()
	wrongSigner.Signer = id2.ID
	verify("self-signer-mismatch", "signer must equal the dh1 id of the embedded key", enc(wrongSigner), envelope.KindAssignment, true)
	verify("key-not-allowed", "a valid signature by a key outside the allowed set", enc(good), envelope.KindAssignment, false, id2.PubString())
	rot, _ := envelope.Sign(id2, id1.ID, envelope.KindRotation, map[string]any{"seq": 1})
	verify("rotated-key-allowed", "a rotated key signs for its genesis id and is checked against the allowed set", enc(rot), envelope.KindRotation, false, id2.PubString())
}

func genAudit(g *gen) {
	l := &audit.Ledger{}
	actions := []string{"cluster-init", "node-enrolled", "app-applied", "admission-allow", "node-revoked"}
	for i, a := range actions {
		l.Append(audit.Entry{TS: 1700000000000 + int64(i)*1000, Actor: ident(1).ID, Source: audit.SourceControl, Action: a,
			Resource: fmt.Sprintf("res/%d", i), Generation: int64(i), Detail: "entry " + fmt.Sprint(i) + " <&> é", Evidence: ""})
	}
	e := l.Entries
	g.add("audit-hash", "first", "domain hash \"audit\" over the entry without its hash field", e[0])
	g.add("audit-hash", "third", "entries commit to prev", e[2])

	cp := func(id *identity.Identity, seq int64, hash string) *envelope.Envelope {
		env, _ := envelope.Sign(id, "", envelope.KindCheckpoint, audit.CheckpointPayload{Ledger: "conformance", Seq: seq, Hash: hash, TS: 1700000009000})
		return env
	}
	keys := map[string][]string{ident(1).ID: {ident(1).PubString()}}
	av := func(id, desc string, entries []audit.Entry, startSeq int64, startPrev string, cps ...*envelope.Envelope) {
		if cps == nil {
			cps = []*envelope.Envelope{}
		}
		g.add("audit-verify", id, desc, map[string]any{"entries": entries, "startSeq": startSeq, "startPrev": startPrev, "checkpoints": cps, "keys": keys})
	}
	cpy := func() []audit.Entry { return append([]audit.Entry{}, e...) }
	av("valid", "an intact chain", e, 0, audit.Genesis)
	av("valid-empty", "an empty chain", []audit.Entry{}, 0, audit.Genesis)
	av("valid-suffix", "a suffix anchored at a trusted predecessor", e[2:], 2, e[1].Hash)
	t1 := cpy()
	t1[2].Detail = "rewritten"
	av("tampered-detail", "a rewritten field breaks the entry hash", t1, 0, audit.Genesis)
	t2 := append(cpy()[:2], e[3:]...)
	av("deleted-entry", "a removed entry is a sequence gap", t2, 0, audit.Genesis)
	t3 := cpy()
	t3[3].Prev = e[1].Hash
	t3[3].Hash = audit.ComputeHash(t3[3])
	av("relinked-entry", "a rehashed entry pointing at the wrong predecessor", t3, 0, audit.Genesis)
	t4 := cpy()
	t4[0].Prev = "b3:" + strings.Repeat("0", 64)
	t4[0].Hash = audit.ComputeHash(t4[0])
	av("bad-genesis", "the first entry must follow genesis", t4, 0, audit.Genesis)
	av("checkpoint-valid", "a signed checkpoint at the head", e, 0, audit.Genesis, cp(ident(1), 5, e[4].Hash), cp(ident(1), 3, e[2].Hash))
	av("checkpoint-truncated", "the ledger ends before a signed checkpoint", e[:3], 0, audit.Genesis, cp(ident(1), 5, e[4].Hash))
	av("checkpoint-mismatch", "a checkpoint for a different history", e, 0, audit.Genesis, cp(ident(1), 4, e[2].Hash))
	av("checkpoint-unknown-key", "a checkpoint signed by a key not allowed for its signer", e, 0, audit.Genesis, cp(ident(2), 5, e[4].Hash))
	forged := cp(ident(1), 5, e[4].Hash)
	forged.Payload = json.RawMessage(strings.Replace(string(forged.Payload), `"seq":5`, `"seq":4`, 1))
	av("checkpoint-forged", "an edited checkpoint payload", e, 0, audit.Genesis, forged)
}

func genCapabilities(g *gen) {
	root, member, host := ident(1), ident(2), ident(3)
	type blk struct {
		Seed    string             `json:"seed"`
		Caveats capability.Caveats `json:"caveats"`
		Next    string             `json:"next"`
		Note    string             `json:"note"`
	}
	mint := func(blocks ...blk) string {
		raw, _ := json.Marshal(map[string]any{"blocks": blocks})
		out, err := Handle("capability-mint", raw)
		if err != nil {
			g.err = err
			return ""
		}
		return out.(map[string]any)["token"].(string)
	}
	rootC := capability.Caveats{Actions: []string{"workload.*"}, Resources: []string{"app/*"}, Expires: 1800000000000}
	memberC := capability.Caveats{Actions: []string{"workload.admit"}, Resources: []string{"app/web/*"}, CPUMaxMilli: 1000, MemMaxBytes: 1 << 30}
	assignC := capability.Caveats{Actions: []string{"workload.admit"}, Resources: []string{"app/web/r0"}, Audience: host.ID, NotBefore: 1700000000000,
		Expires: 1700003600000, Generation: 7, Digest: "b3:" + strings.Repeat("ab", 32), CPUMaxMilli: 500, MemMaxBytes: 256 << 20}
	b0 := blk{Seed: Seed(1), Caveats: rootC, Next: member.PubString(), Note: "member delegation"}
	b1 := blk{Seed: Seed(2), Caveats: memberC, Next: host.PubString(), Note: "web replicas"}
	b2 := blk{Seed: Seed(3), Caveats: assignC, Next: "", Note: "assignment web/r0 generation 7"}

	for _, m := range []struct {
		id     string
		blocks []blk
	}{{"root-only", []blk{b0}}, {"two-blocks", []blk{b0, b1}}, {"three-blocks", []blk{b0, b1, b2}}} {
		raw := map[string]any{"blocks": m.blocks}
		g.add("capability-mint", m.id, "dhcap1. + base64url(canonical([block envelopes]))", raw)
	}
	full := mint(b0, b1, b2)
	req := map[string]any{"action": "workload.admit", "resource": "app/web/r0", "audience": host.ID, "now": int64(1700000100000),
		"generation": int64(7), "digest": "b3:" + strings.Repeat("ab", 32), "cpuMilli": int64(500), "memBytes": int64(256 << 20)}
	with := func(k string, v any) map[string]any {
		out := map[string]any{}
		for kk, vv := range req {
			out[kk] = vv
		}
		out[k] = v
		return out
	}
	roots := []string{root.PubString()}
	cv := func(id, desc, tok string, rts []string, r map[string]any) {
		g.add("capability-verify", id, desc, map[string]any{"token": tok, "roots": rts, "request": r})
	}
	cv("valid", "every block's caveats hold", full, roots, req)
	cv("untrusted-root", "block 0 must be signed by a trusted root", full, []string{member.PubString()}, req)
	cv("wrong-action", "action not granted", full, roots, with("action", "workload.stop"))
	cv("wrong-resource", "resource not granted by the assignment block", full, roots, with("resource", "app/web/r1"))
	cv("outside-member-scope", "the member block narrows app/* to app/web/*", mint(b0, b1, blk{Seed: Seed(3), Caveats: capability.Caveats{Actions: []string{"workload.admit"}, Resources: []string{"app/db/r0"}}}), roots, with("resource", "app/db/r0"))
	cv("audience", "the assignment is for another host", full, roots, with("audience", member.ID))
	cv("not-yet-valid", "now < notBefore", full, roots, with("now", int64(1699999999999)))
	cv("expires-boundary", "now == expires is expired", full, roots, with("now", int64(1700003600000)))
	cv("just-before-expiry", "now == expires-1 is valid", full, roots, with("now", int64(1700003599999)))
	cv("generation", "bound to generation 7", full, roots, with("generation", int64(8)))
	cv("digest", "bound to an artifact digest", full, roots, with("digest", "b3:"+strings.Repeat("cd", 32)))
	cv("cpu-limit", "500m limit", full, roots, with("cpuMilli", int64(501)))
	cv("mem-limit", "256 MiB limit", full, roots, with("memBytes", int64(256<<20+1)))
	cv("member-cpu-limit", "the member block limits cpu to 1000m even if a later block is wider",
		mint(b0, b1, blk{Seed: Seed(3), Caveats: capability.Caveats{Actions: []string{"workload.admit"}, Resources: []string{"app/web/r0"}, CPUMaxMilli: 4000}}),
		roots, with("cpuMilli", int64(2000)))
	cv("nested-resource", "app/* also covers nested app/web/r0 (prefix rule)", mint(b0), roots, map[string]any{"action": "workload.admit", "resource": "app/web/r0", "now": int64(1700000000000)})
	cv("glob-question", "path.Match ? wildcard", mint(blk{Seed: Seed(1), Caveats: capability.Caveats{Actions: []string{"*"}, Resources: []string{"app/w?b"}}}), roots, map[string]any{"action": "x", "resource": "app/web"})
	cv("glob-class", "path.Match character class with negation", mint(blk{Seed: Seed(1), Caveats: capability.Caveats{Actions: []string{"*"}, Resources: []string{"vol/[^x]*"}}}), roots, map[string]any{"action": "x", "resource": "vol/data"})
	cv("glob-class-negated", "negated class excludes x", mint(blk{Seed: Seed(1), Caveats: capability.Caveats{Actions: []string{"*"}, Resources: []string{"vol/[^x]*"}}}), roots, map[string]any{"action": "x", "resource": "vol/xdata"})
	cv("glob-star-no-slash", "* does not cross / (without the trailing /* prefix rule)", mint(blk{Seed: Seed(1), Caveats: capability.Caveats{Actions: []string{"*"}, Resources: []string{"app/*-db"}}}), roots, map[string]any{"action": "x", "resource": "app/a/b-db"})
	cv("action-prefix-wildcard", "workload.* does not cover workloadX", mint(b0), roots, map[string]any{"action": "workloadX", "resource": "app/a", "now": int64(1)})
	cv("wrong-delegate", "block 1 signed by a key other than block 0's next", mint(b0, blk{Seed: Seed(4), Caveats: memberC, Next: host.PubString()}), roots, req)
	cv("sealed", "a block after a sealed block", mint(b0, b1, b2, blk{Seed: Seed(3), Caveats: assignC}), roots, req)
	tampered := strings.Replace(full, full[len(full)-40:len(full)-30], strings.Repeat("A", 10), 1)
	cv("tampered-encoding", "a corrupted token", tampered, roots, req)
	if tok, err := capability.Decode(full); err == nil {
		edited := *tok.Blocks[1]
		edited.Payload = json.RawMessage(strings.Replace(string(edited.Payload), `"note":"web replicas"`, `"note":"web replicas!"`, 1))
		tok.Blocks[1] = &edited
		cv("tampered-block", "an edited block payload fails that block's signature", tok.Encode(), roots, req)
	}
	cv("missing-prefix", "tokens start with dhcap1.", strings.TrimPrefix(full, "dhcap1."), roots, req)
	var many []blk
	for i := 0; i < 17; i++ {
		many = append(many, blk{Seed: Seed(1), Caveats: rootC, Next: root.PubString()})
	}
	cv("too-many-blocks", "at most 16 blocks", mint(many...), roots, req)
}

func genStorage(g *gen) {
	type dg struct {
		Alg    string `json:"alg"`
		Seed   uint64 `json:"seed"`
		Length int    `json:"length"`
	}
	cases := []struct {
		id, desc string
		d        dg
	}{
		{"empty", "no data, no chunks", dg{"zero", 0, 0}},
		{"one-byte", "a single byte", dg{"xorshift64*", 1, 1}},
		{"min", "exactly the 16 KiB minimum", dg{"xorshift64*", 2, storage.MinChunk}},
		{"min-plus-one", "one byte over the minimum", dg{"xorshift64*", 3, storage.MinChunk + 1}},
		{"random-70k", "random data around the average size", dg{"xorshift64*", 4, 70000}},
		{"random-600k", "random data, several content-defined cuts", dg{"xorshift64*", 5, 600000}},
		{"zeros-600k", "low-entropy data is cut at the 256 KiB maximum", dg{"zero", 0, 600000}},
		{"pattern-300k", "a repeating pattern", dg{"pattern", 0, 300000}},
	}
	for _, c := range cases {
		g.add("chunk", c.id, c.desc+" (FastCDC 16/64/256 KiB, BLAKE3-derived gear table)", map[string]any{"data_gen": c.d})
	}
	id := func(s string) string { return storage.ChunkID([]byte(s)) }
	sets := []struct {
		id, desc string
		ids      []string
	}{
		{"empty", "the empty set is BLAKE3(0x02)", []string{}},
		{"one", "a single leaf", []string{id("a")}},
		{"two", "one node", []string{id("a"), id("b")}},
		{"three", "an odd node is promoted unchanged", []string{id("a"), id("b"), id("c")}},
		{"unsorted-duplicates", "ids are de-duplicated and sorted first", []string{id("c"), id("a"), id("b"), id("a")}},
		{"seven", "two promotions", []string{id("1"), id("2"), id("3"), id("4"), id("5"), id("6"), id("7")}},
	}
	for _, s := range sets {
		g.add("merkle", s.id, s.desc, map[string]any{"ids": s.ids})
	}
}
