// Package pki derives X.509 material from dh identities.
//
// The cluster root Ed25519 key is also an X.509 CA. It issues TLS
// certificates to control-plane members (Raft peer transport and the API
// listener), so every TLS trust decision chains to the same root key that
// hosts pin when they join. A separate cluster-local ECDSA CA (generated by
// the control plane) issues certificates for `tls: local` ingress, because
// browsers do not accept Ed25519 server certificates.
package pki

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"net"
	"time"

	"decentralized.host/pkg/identity"
)

func serial() *big.Int {
	n, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 126))
	if err != nil {
		panic(err)
	}
	return n
}

// RootCA creates the self-signed root CA certificate for a cluster.
func RootCA(root *identity.Identity, cluster string) ([]byte, error) {
	tmpl := &x509.Certificate{
		SerialNumber:          serial(),
		Subject:               pkix.Name{CommonName: "dh root " + cluster, Organization: []string{"Decentralized.Host"}},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().AddDate(20, 0, 0),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLenZero:        true,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, root.Pub, root.Priv)
	if err != nil {
		return nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), nil
}

// IssueMember issues a TLS certificate for a control-plane member key.
func IssueMember(root *identity.Identity, caPEM []byte, memberPub ed25519.PublicKey, hosts []string) ([]byte, error) {
	ca, err := ParseCert(caPEM)
	if err != nil {
		return nil, err
	}
	tmpl := &x509.Certificate{
		SerialNumber: serial(),
		Subject:      pkix.Name{CommonName: identity.NodeID(memberPub), Organization: []string{"Decentralized.Host control plane"}},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().AddDate(5, 0, 0),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
	}
	addHosts(tmpl, append(hosts, "localhost", "127.0.0.1", identity.NodeID(memberPub)))
	der, err := x509.CreateCertificate(rand.Reader, tmpl, ca, memberPub, root.Priv)
	if err != nil {
		return nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), nil
}

func addHosts(tmpl *x509.Certificate, hosts []string) {
	seen := map[string]bool{}
	for _, h := range hosts {
		if h == "" || seen[h] {
			continue
		}
		seen[h] = true
		if host, _, err := net.SplitHostPort(h); err == nil {
			h = host
		}
		if ip := net.ParseIP(h); ip != nil {
			tmpl.IPAddresses = append(tmpl.IPAddresses, ip)
		} else {
			tmpl.DNSNames = append(tmpl.DNSNames, h)
		}
	}
}

// ParseCert decodes the first PEM certificate.
func ParseCert(p []byte) (*x509.Certificate, error) {
	block, _ := pem.Decode(p)
	if block == nil || block.Type != "CERTIFICATE" {
		return nil, errors.New("pki: not a PEM certificate")
	}
	return x509.ParseCertificate(block.Bytes)
}

// Fingerprint returns the SHA-256 fingerprint of a DER certificate.
func Fingerprint(der []byte) string {
	sum := sha256.Sum256(der)
	return "sha256:" + hex.EncodeToString(sum[:])
}

// MemberTLS builds a TLS config that presents the member certificate and
// requires peers to present a certificate issued by the root CA. allow, if
// set, further restricts which peer keys are accepted (the current roster).
func MemberTLS(id *identity.Identity, certPEM, caPEM []byte, allow func(pub string) bool) (*tls.Config, error) {
	cert, err := ParseCert(certPEM)
	if err != nil {
		return nil, err
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, errors.New("pki: bad CA PEM")
	}
	verify := func(raw [][]byte, _ [][]*x509.Certificate) error {
		if len(raw) == 0 {
			return errors.New("pki: peer presented no certificate")
		}
		peer, err := x509.ParseCertificate(raw[0])
		if err != nil {
			return err
		}
		if _, err := peer.Verify(x509.VerifyOptions{Roots: pool, KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageAny}}); err != nil {
			return fmt.Errorf("pki: peer certificate not issued by cluster root: %w", err)
		}
		pub, ok := peer.PublicKey.(ed25519.PublicKey)
		if !ok {
			return errors.New("pki: peer key is not Ed25519")
		}
		if allow != nil && !allow(identity.EncodePub(pub)) {
			return fmt.Errorf("pki: peer %s is not in the current roster", identity.NodeID(pub))
		}
		return nil
	}
	return &tls.Config{
		MinVersion:            tls.VersionTLS13,
		Certificates:          []tls.Certificate{{Certificate: [][]byte{cert.Raw}, PrivateKey: id.Priv, Leaf: cert}},
		ClientAuth:            tls.RequireAnyClientCert,
		InsecureSkipVerify:    true, // replaced by VerifyPeerCertificate (chain to root + roster)
		VerifyPeerCertificate: verify,
	}, nil
}

// ClientTLS verifies a server certificate chains to the pinned root CA.
func ClientTLS(caPEM []byte) (*tls.Config, error) {
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, errors.New("pki: bad CA PEM")
	}
	return &tls.Config{
		MinVersion:         tls.VersionTLS13,
		InsecureSkipVerify: true,
		VerifyPeerCertificate: func(raw [][]byte, _ [][]*x509.Certificate) error {
			if len(raw) == 0 {
				return errors.New("pki: server presented no certificate")
			}
			c, err := x509.ParseCertificate(raw[0])
			if err != nil {
				return err
			}
			_, err = c.Verify(x509.VerifyOptions{Roots: pool, KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth}})
			return err
		},
	}, nil
}

// NewLocalCA creates the cluster-local ECDSA CA.
func NewLocalCA(cluster string) (certPEM, keyPEM []byte, err error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, err
	}
	tmpl := &x509.Certificate{
		SerialNumber:          serial(),
		Subject:               pkix.Name{CommonName: "dh local CA " + cluster, Organization: []string{"Decentralized.Host"}},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().AddDate(10, 0, 0),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return nil, nil, err
	}
	kder, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return nil, nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: kder}), nil
}

// SignLocal issues a leaf certificate for pub from the local CA.
func SignLocal(caCertPEM, caKeyPEM []byte, pub crypto.PublicKey, names []string, validity time.Duration) ([]byte, error) {
	ca, err := ParseCert(caCertPEM)
	if err != nil {
		return nil, err
	}
	block, _ := pem.Decode(caKeyPEM)
	if block == nil {
		return nil, errors.New("pki: bad CA key")
	}
	key, err := x509.ParseECPrivateKey(block.Bytes)
	if err != nil {
		return nil, err
	}
	tmpl := &x509.Certificate{
		SerialNumber: serial(),
		Subject:      pkix.Name{CommonName: names[0]},
		NotBefore:    time.Now().Add(-5 * time.Minute),
		NotAfter:     time.Now().Add(validity),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	addHosts(tmpl, names)
	der, err := x509.CreateCertificate(rand.Reader, tmpl, ca, pub, key)
	if err != nil {
		return nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), nil
}

// BootstrapCert is a throwaway self-signed certificate a member serves
// before it has root-issued credentials. The operator pins it by
// fingerprint (written next to the bootstrap code), so the one-time code
// and the member credentials never cross the network in cleartext.
func BootstrapCert() (tls.Certificate, string, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return tls.Certificate{}, "", err
	}
	tmpl := &x509.Certificate{
		SerialNumber: serial(),
		Subject:      pkix.Name{CommonName: "dh member awaiting bootstrap"},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().AddDate(0, 0, 30),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return tls.Certificate{}, "", err
	}
	return tls.Certificate{Certificate: [][]byte{der}, PrivateKey: key}, Fingerprint(der), nil
}

// PinnedTLS accepts exactly one server certificate, identified by its
// fingerprint, regardless of issuer or name.
func PinnedTLS(fingerprint string) *tls.Config {
	return &tls.Config{
		MinVersion:         tls.VersionTLS13,
		InsecureSkipVerify: true, // replaced by the pin below
		VerifyPeerCertificate: func(raw [][]byte, _ [][]*x509.Certificate) error {
			if len(raw) == 0 || Fingerprint(raw[0]) != fingerprint {
				return fmt.Errorf("pki: server certificate does not match pinned fingerprint %s", fingerprint)
			}
			return nil
		},
	}
}
